---
version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7.3-stretch

    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: install pipenv
          command: |
            python3 -m pip install pipenv --user

      # Download and cache dependencies
      # - restore_cache:
      #     keys:
      #       - v1-dependencies-{{ checksum "requirements.txt" }}
      #       # fallback to using the latest cache if no exact match is found
      #       - v1-dependencies-

      - run:
          name: install deps
          command: |
            pipenv install --dev --deploy

      # - save_cache:
      #     paths:
      #       - ./venv
      #     key: v1-dependencies-{{ checksum "requirements.txt" }}

      - run:
          name: run tests
          command: |
            pipenv run python -m pytest .

      - run:
          name: run mypy
          command: |
            pipenv run mypy eggman/ --ignore-missing-imports

      - run:
          name: ensure black format
          command: |
            pipenv run black -l 110 . --check

      - run:
          name: code coverage
          command: |
            pipenv run python -m pytest --cov-report=xml --cov=jab/ test/

      - run:
          name: codecov upload
          command: |
            pipenv install codecov
            pipenv run codecov
